trigger:
  branches:
    include:
      - main

variables:
  NODE_VERSION: '20.x'
  ALLURE_REPORT_DIR: 'allure-report'

stages:
- stage: TestExecution
  displayName: Execute WDIO Tests

  jobs:
    - job: RunTests

      pool:
        vmImage: ubuntu-latest

      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          displayName: Install Node.js
          inputs:
            versionSpec: $(NODE_VERSION)

        - script: npm ci
          displayName: Install Dependencies

        - script: |
            npx wdio run wdio.conf.js
          displayName: Run WDIO Tests

        - script: |
            npx allure generate allure-results \
              --clean \
              -o $(ALLURE_REPORT_DIR)
          displayName: Generate Allure Report
          condition: always()

        - task: PublishPipelineArtifact@1
          displayName: Publish Allure Report
          condition: always()
          inputs:
            targetPath: $(Build.SourcesDirectory)/$(ALLURE_REPORT_DIR)
            artifact: allure-report

- stage: SendEmailNotification
  displayName: "Sending email to user with allure report as attachment"

  jobs:
    - job: SendEmail

      pool:
        vmImage: ubuntu-latest

      steps:
        - checkout: self
          clean: true

        - task: DownloadPipelineArtifact@2
            inputs:
            artifact: allure-report
            path: $(Pipeline.Workspace)/allure-report

        - script: | 
            set -e

            ZIP_PATH="$(Build.ArtifactStagingDirectory)/allure-report.zip"

            cd "$(Pipeline.Workspace)/$(ALLURE_REPORT_DIR)"
            zip -r $ZIP_PATH .

            ENCODED=$(base64 "$ZIP_PATH" | tr -d '\n')

            curl -X POST "https://api.resend.com/emails" \
              -H "Authorization: Bearer $RESEND_EMAIL_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{
                \"from\": \"onboarding@resend.dev\",
                \"to"\: \"s4.islam@a1qa.com\",
                \"subject"\: \"Allure Report\",
                \"html"\: \"<p>Attached is the latest build Allure Report.</p>\",
                \"attachments"\: [{
                  \"filename\": \"allure-report.zip\",
                  \"content\": \"${ENCODED}\",
                  \"type\": \"application/zip\"
                }]
              }"
          displayName: "Send Allure Report via Resend"    
          env:
            RESEND_EMAIL_API_KEY: $(RESEND_EMAIL_API_KEY)
            